CREATE SEQUENCE TASK_CONFIG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE PAPER_ROLL_STATUS_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE TRANSUMMARY_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE EMAIL_CONFIG_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE TASK_CONFIG (
	ID NUMBER(10,0) DEFAULT "WPTSAPN"."TASK_CONFIG_SEQ".nextval,
	CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"ACTION" VARCHAR2(30),
	CRON VARCHAR2(30),
	ISENABLED NUMBER(1,0) DEFAULT 0,
	PERIOD NUMBER(10,0),
	VALUE NUMBER(10,0),
	CONSTRAINT SYS_C0020176 CHECK ("ID" IS NOT NULL),
	CONSTRAINT SYS_C0020177 CHECK ("ACTION" IS NOT NULL),
	CONSTRAINT SYS_C0020178 CHECK ("CRON" IS NOT NULL),
	CONSTRAINT SYS_C0020179 CHECK ("PERIOD" IS NOT NULL),
	CONSTRAINT SYS_C0020180 CHECK ("VALUE" IS NOT NULL),
	CONSTRAINT SYS_C0020181 PRIMARY KEY (ID)
);

CREATE TABLE PAPER_ROLL_STATUS (
	ID NUMBER(10,0) DEFAULT "WPTSAPN"."PAPER_ROLL_STATUS_SEQ".nextval,
	CREATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	UPDATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	REQDATE DATE,
	MERCHANTID NUMBER(10,0),
	SERIALNO VARCHAR2(150),
	CONTACTNUMBER VARCHAR2(100),
	CONTACTPERSON VARCHAR2(100),
	REMARKS VARCHAR2(1000),
	"TYPE" VARCHAR2(200),
	TERMINALID NUMBER(38,0),
	CONSTRAINT SYS_C0020326 CHECK ("ID" IS NOT NULL),
	CONSTRAINT SYS_C0020327 PRIMARY KEY (ID)
);

ALTER TABLE WPTSAPN.PAPER_ROLL_STATUS ADD CONSTRAINT FK2SE7TBUMSWUKQ6YP6O2WTFWG6 FOREIGN KEY (MERCHANTID) REFERENCES MERCHANTS(ID);
ALTER TABLE WPTSAPN.PAPER_ROLL_STATUS ADD CONSTRAINT SYS_C0045772 FOREIGN KEY (TERMINALID) REFERENCES TERMINALS(ID) ON DELETE SET NULL;

CREATE TABLE TRANSUMMARY (
	ID NUMBER(10,0) DEFAULT "WPTSAPN"."TRANSUMMARY_SEQ".nextval,
	AMOUNT NUMBER(10,0),
	AUTHCODE VARCHAR2(20),
	BATCHNO NUMBER(10,0),
	BATCHID NUMBER(10,0),
	CARDLABEL VARCHAR2(20),
	CREATEDAT TIMESTAMP,
	CURRENCY VARCHAR2(6),
	CUSTMOBILE VARCHAR2(12),
	DATETIME TIMESTAMP,
	DCCCURRENCY VARCHAR2(50),
	DCCTRANAMOUNT NUMBER(10,0),
	ENTRYMODE VARCHAR2(50),
	EXPDATE VARCHAR2(5),
	INVOICENO NUMBER(10,0),
	ISAWAY NUMBER(1,0),
	ISNOTIFIED NUMBER(1,0) DEFAULT 0,
	ISPROCESSED NUMBER(1,0) DEFAULT 0,
	LAT FLOAT,
	LNG FLOAT,
	MERCHANTID NUMBER(10,0),
	NII VARCHAR2(5),
	ORIGINID VARCHAR2(65),
	PAN VARCHAR2(25),
	PAYMENTMODE VARCHAR2(10),
	RRN VARCHAR2(20),
	SIGNDATA CLOB,
	TERMINALID NUMBER(10,0),
	TIPAMOUNT NUMBER(10,0),
	TRACENO NUMBER(10,0),
	TRANSTYPE VARCHAR2(20),
	UPDATEDAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	ISVOIDED NUMBER(1,0),
	ORITRACENO NUMBER(10,0),
	ORITRANSTYPE VARCHAR2(20),
	ORIBATCHNO NUMBER(10,0),
	ORIDATETIME TIMESTAMP,
	ORIRRN VARCHAR2(20),
	ORIAUTHCODE VARCHAR2(20),
	ORISIGNDATA CLOB,
	CONSTRAINT SYS_C0021383 CHECK ("ID" IS NOT NULL),
	CONSTRAINT SYS_C0021384 CHECK ("AMOUNT" IS NOT NULL),
	CONSTRAINT SYS_C0021385 CHECK ("CURRENCY" IS NOT NULL),
	CONSTRAINT SYS_C0021386 CHECK ("ORIGINID" IS NOT NULL),
	CONSTRAINT SYS_C0021387 CHECK ("PAYMENTMODE" IS NOT NULL),
	CONSTRAINT SYS_C0021388 PRIMARY KEY (ID)
);

CREATE TABLE EMAIL_CONFIG (
	ID NUMBER(38,0) DEFAULT "WPTSAPN"."EMAIL_CONFIG_SEQ".nextval,
	"ACTION" NVARCHAR2(30),
	BCC NVARCHAR2(500),
	CC NVARCHAR2(500),
	TO_LIST NVARCHAR2(500),
	CREATEDAT TIMESTAMP WITH LOCAL TIME ZONE,
	UPDATEDAT TIMESTAMP WITH LOCAL TIME ZONE,
	CONSTRAINT SYS_C0020107 CHECK ("ID" IS NOT NULL),
	CONSTRAINT SYS_C0020108 CHECK ("ACTION" IS NOT NULL),
	CONSTRAINT SYS_C0020109 CHECK ("CREATEDAT" IS NOT NULL),
	CONSTRAINT SYS_C0020110 CHECK ("UPDATEDAT" IS NOT NULL),
	CONSTRAINT SYS_C0020111 PRIMARY KEY (ID),
	CONSTRAINT UNIQUE_ACTION UNIQUE ("ACTION")
);
