DROP TABLE IF EXISTS CBADigitalReceipt.dbo.RECEIPT_DETAILS ;
DROP TABLE IF EXISTS CBADigitalReceipt.dbo.Transactions ;

CREATE TABLE CBADigitalReceipt.dbo.Transactions (
	id bigint IDENTITY(1,1) NOT NULL,
	originId varchar(65) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	paymentMode varchar(10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	custMobile varchar(12) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	transType varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	cardLabel varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	terminalId bigint NULL,
	batchId bigint NULL,
	traceNo bigint NULL,
	invoiceNo bigint NULL,
	amount bigint NOT NULL,
	currency varchar(6) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	batchNo bigint NULL,
	pan varchar(25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[dateTime] datetime2 NOT NULL,
	expDate varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	nii varchar(5) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	rrn varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	authCode varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	signData varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	tipAmount bigint NULL,
	entryMode varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	dccCurrency varchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	dccTranAmount bigint NULL,
	isVoided bit DEFAULT 0 NULL,
	lat float NULL,
	lng float NULL,
	isAway bit NULL,
	oriTraceNo bigint NULL,
	oriTransType varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	oriBatchNo bigint NULL,
	oriDateTime datetime2 NULL,
	oriRrn varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	oriAuthCode varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	oriSignData varchar(MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	createdAt datetime2 NOT NULL,
	updatedAt datetime2 NOT NULL,
	merchantId bigint NULL,
	CONSTRAINT PK__Transact__3213E83F4B291826 PRIMARY KEY (id),
	CONSTRAINT FK__Transacti__batch__03DB89B3 FOREIGN KEY (batchId) REFERENCES CBADigitalReceipt.dbo.Batches(id),
	CONSTRAINT FK__Transacti__merch__04CFADEC FOREIGN KEY (merchantId) REFERENCES CBADigitalReceipt.dbo.Merchants(id),
	CONSTRAINT FK__Transacti__termi__02E7657A FOREIGN KEY (terminalId) REFERENCES CBADigitalReceipt.dbo.Terminals(id) ON DELETE CASCADE
);

CREATE TABLE CBADigitalReceipt.dbo.EReceipts (
	id bigint IDENTITY(1,1) NOT NULL,
	email varchar(40) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	contactNo varchar(15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	receiptType varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	eReceiptCategory varchar(20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	isSentMail bit DEFAULT 0 NULL,
	isSentSMS bit DEFAULT 0 NULL,
	transactionId bigint NULL,
	batchId bigint NULL,
	createdAt datetime2 NOT NULL,
	updatedAt datetime2 NOT NULL,
	CONSTRAINT PK__EReceipt__3213E83F6B889BF6 PRIMARY KEY (id),
	CONSTRAINT FK__EReceipts__batch__2354350C FOREIGN KEY (batchId) REFERENCES CBADigitalReceipt.dbo.Batches(id),
	CONSTRAINT FK__EReceipts__trans__226010D3 FOREIGN KEY (transactionId) REFERENCES CBADigitalReceipt.dbo.Transactions(id) ON DELETE CASCADE
);
